[project]
name = "evals"
version = "0.1.0"
description = ""
dependencies = [
    "python-dotenv"
]

[project.optional-dependencies]
ifeval = [
    "immutabledict",
    "nltk",
    "langdetect",
    "absl-py",
]

mt_bench = [
    "shortuuid",
    "anthropic",
    "openai",
]

gsm8k = [
    "datasets",
    "absl-py"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
